### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#283]
Report of error uploading file.... logs say:

```
2019-05-20 19:45:39,175 ERROR (Thread-119) [DatasetController(lambda$validate$1:286)] Exception during dataset validation
java.util.concurrent.CompletionException: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT data, expedition_code AS "expeditionCode" FROM network_1.Tissue t JOIN expeditions e on t.expedition_id = e.id WHERE t.parent_identifier in () and e.project_id = ?
]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 149
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT data, expedition_code AS "expeditionCode" FROM network_1.Tissue t JOIN expeditions e on t.expedition_id = e.id WHERE t.parent_identifier in () and e.project_id = ?
]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 149
    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
    at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
    at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:199)
    at biocode.fims.tissues.PostgresTissueRepository.getTissues(PostgresTissueRepository.java:53)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
    at com.sun.proxy.$Proxy1705.getTissues(Unknown Source)
    at biocode.fims.tissues.reader.TissueConverter.getExistingRecords(TissueConverter.java:198)
    at biocode.fims.tissues.reader.TissueConverter.convertRecordSet(TissueConverter.java:67)
    at biocode.fims.run.DatasetBuilder.runDataConverters(DatasetBuilder.java:350)
    at biocode.fims.run.DatasetBuilder.build(DatasetBuilder.java:113)
    at biocode.fims.run.DatasetProcessor.validate(DatasetProcessor.java:97)
    at biocode.fims.rest.services.DatasetController.lambda$validate$0(DatasetController.java:220)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
```

**Comment by ewingrj** [comment]
fixed in biocodellc/biocode-fims-tissues@f9e2614c11
