### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#5]
On clean npm install, running without yarn, status fails with:

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/style/app.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/jdeck/IdeaProjects/geome3/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jdeck/IdeaProjects/geome3/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
 @ ./src/style/app.scss 4:14-164
 @ ./src/app/app.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/app/app.js
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 1.17 kB [entry] [rendered]
webpack: Failed to compile.

**Comment by rodney757** [comment]
works fine on my computer.

can you update to npm version >= `5.6.0`. I know early `5.x.x` versions are buggy. I'm using `5.6.0` w/o issues

**Comment by jdeck88** [comment]
I updated node to 5.6.0 and it still failed.   From one of the comments at https://github.com/sass/node-sass/issues/1579, i saw this tip to address the sass-loader library, which doesn't install correctly when part of a larger set of downloads:

npm update
npm install
nodejs node_modules/node-sass/scripts/install.js
npm rebuild node-sass

**Comment by jdeck88** [comment]
another (easier) method than above is to uninstall node-sass and then re-install it.
